export const propertyData = [
  {
    id: "1",
    name: "Luxury Apartment",
    price: 120,
    location: "New York, NY",
    propertyType: "Villa",
    latitude: 40.7128,
    longitude: -74.006,
    bed: 3,
    bath: 2,
    distance: 10,
    broker: "John Doe",
    description: "A beautiful luxury apartment.",
    image: require("@/assets/images/house3.webp"),
    status: "Pending",
  },
  {
    id: "2",
    name: "Modern Villa",
    price: 250,
    location: "Los Angeles, CA",
    propertyType: "Apartment",
    latitude: 34.0522,
    longitude: -118.2437,
    bed: 4,
    bath: 3,
    distance: 15,
    broker: "Jane Smith",
    description: "A spacious and modern villa.",
    image: require("@/assets/images/house2.jpg"),
    status: "For sale",
  },
  {
    id: "3",
    name: "Modern Villa",
    price: 2500000,
    location: "Los Angeles, CA",
    propertyType: "Rentals",
    latitude: 34.0522,
    longitude: -118.2437,
    bed: 4,
    bath: 3,
    distance: 20,
    broker: "Emily Johnson",
    description:
      "A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.",
    image: require("@/assets/images/house4.jpg"),
    status: "Rented",
  },
  {
    id: "4",
    name: "Modern Villa",
    price: 2500000,
    location: "Los Angeles, CA",
    propertyType: "Apartment",
    latitude: 34.0522,
    longitude: -118.2437,
    bed: 4,
    bath: 3,
    distance: 15,
    broker: "Jane Smith",
    description: "A spacious and modern villa.",
    image: require("@/assets/images/house2.jpg"),
    status: "For sale",
  },
  {
    id: "5",
    name: "Modern Villa",
    price: 2500000,
    location: "Los Angeles, CA",
    propertyType: "Rentals",
    latitude: 34.0522,
    longitude: -118.2437,
    bed: 4,
    bath: 3,
    distance: 20,
    broker: "Emily Johnson",
    description:
      "A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.A modern villa with a great view.",
    image: require("@/assets/images/house4.jpg"),
    status: "Rented",
  },
];
