name: Simple CI/CD for Estate App
# WHEN does this workflow run?
# Every time you push code to the "main" branch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
# WHAT version of Node.js to use (matches your React Native needs)

env:
  NODE_VERSION: '18'
# JOBS are the tasks that run (think of them as steps in a recipe)

jobs:
  # JOB 1: Check if your code is good (linting, type checking)
  code-quality:
    name: 'Check Code quality'
    runs-on: ubuntu-latest

    steps:
      # STEP 1: Get your code from GitHub
      - name: 'Get the code'
        uses: actions/checkout@v4

      # STEP 2: Install Node.js (JavaScript runtime)
      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Enable Corepack'
        run: corepack enable

      - name: 'Prepare Yarn 4'
        run: corepack prepare yarn@4 --activate

      - name: 'Cache Yarn artifacts'
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # STEP 3: Install your app's dependencies (like yarn install)
      - name: 'Install dependencies'
        run: |
          yarn install --immutable

      # STEP 4: Check if TypeScript code has errors
      - name: 'Check Typescript types'
        run: yarn type-check

      # STEP 5: Check if code follows style rules
      - name: 'Run ESLint'
        run: yarn lint

      # STEP 6: Check code formatting (we'll add this script)
      - name: 'Check code formatting'
        run: yarn format:check

  # JOB 2: Build your app (only runs if code quality passes)
  build-app:
    name: 'Build the app'
    runs-on: ubuntu-latest
    needs: code-quality # This job runs only if "code-quality" job is successful
    if: github.ref == 'refs/heads/main' # Only builds on main branch

    steps:
      - name: 'Get the code'
        uses: actions/checkout@v4

      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Enable Corepack'
        run: corepack enable

      - name: 'Prepare Yarn 4'
        run: corepack prepare yarn@4 --activate

      - name: 'Cache Yarn artifacts'
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 'Install dependencies'
        run: |
          yarn install --immutable

      # Check if the app can be built (without actually building the full app)
      - name: 'Test Native Build'
        run: yarn dlx expo prebuild --no-install

      - name: 'Build Successful!'
        run: echo "Your app builds successfully!"
